/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    EditForm: typeof import('./components/session/EditForm.vue')['default']
    FormDialog: typeof import('./components/auth/FormDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionCard: typeof import('./components/session/SessionCard.vue')['default']
    SignInForm: typeof import('./components/auth/SignInForm.vue')['default']
    SignUpForm: typeof import('./components/auth/SignUpForm.vue')['default']
  }
}
