services:

  postgres:
    image: postgres:16.1
    ports: 
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "rd_postgres_data:/var/lib/postgresql/data"

volumes:
  rd_postgres_data: